### PR TITLE
Improve UX for multiple split `masterIdentities`

### LINKED ISSUE #24: Improve UX for multiple split `masterIdentities`
I have a project which is maintained by multiple persons. Each person requires the ability to create new secrets with their personal split identity, associated with their Yubikey.

## Single master identity
Having multiple split keys as a single user is usually not a problem, since normally only one of them is used as the primary key, allowing one to choose the following configuration:
``` nix
age.rekey = {
  masterIdentities = [ ./primary-split-identity.pub ];
  extraEncryptionPubkeys = [ ./secondary-recipients.pub ];
};
```
Contents of `./primary-split-identity.pub`, usually as generated by the Yubikey tooling:
```
#       Serial: 00000000, Slot: 00
#         Name: Some Name
#      Created: Mon, 01 Jan 2000 00:00:00 +0000
#   PIN policy: Once   (A PIN is required once per session, if set)
# Touch policy: Always (A physical touch is required for every decryption)
#    Recipient: age1yubikey1<primary-pubkey>
AGE-PLUGIN-YUBIKEY-<primary-split-identity>
```
Contents of `./secondary-recipients.pub`, usually assembled by manually copying the pubkeys:
```
age1yubikey1<secondary-pubkey>
```
For this setup, it does not matter whether or not the secondary identities are split-identities or not, since the pubkeys are manually collected, anyways.

## Multiple master identities
The situation changes however, if one considers the following configuration with two split `masterIdentities`:
``` nix
age.rekey = {
  masterIdentities = [
    ./primary-split-identity.pub
    ./secondary-split-identity.pub
  ];
};
```
The `./secondary-split-identity.pub` contains:
```
#       Serial: 11111111, Slot: 00
#         Name: Some Other Name
#      Created: Mon, 01 Jan 2000 00:00:00 +0000
#   PIN policy: Once   (A PIN is required once per session, if set)
# Touch policy: Always (A physical touch is required for every decryption)
#    Recipient: age1yubikey1<secondary-pubkey>
AGE-PLUGIN-YUBIKEY-<secondary-split-identity>
```
If one only has one of the Yubikeys plugged in and attempts to edit an encrypted file using `agenix edit` (I am assuming `rage` and `age-plugin-yubikey` for the backing implementations), the decryption works fine, since only one working key is necessary for decryption. However, on saving the file, the implementation of `rage`/`age-plugin-yubikey` prompts for every split identity. If you try to skip one of the identities, you will get this output:
```
Collecting information about hosts. This may take a while...
Error: '⁨age-plugin-yubikey⁩' couldn't use an identity: ⁨Could not open YubiKey with serial 11111111

[ Did rage not do what you expected? Could an error be more useful? ]
[ Tell us: https://str4d.xyz/rage/report                            ]
error: Failed to (re)encrypt edited file, original is left unchanged.
```
Equivalent behavior is obtained when invoking the following command directly:
``` sh
echo "test" | rage -e -i ./primary-split-identity.pub -i ./secondary-split-identity.pub > ./test.age
```
As it appears, the backing implementation requires physical presence of all Yubikeys to derive the pubkey for each one, instead of looking at the `Recipient:` field in the preceding comment. While I would certainly consider this primarily an upstream issue, I think it still could be meaningful if `agenix-rekey` could work around this.

## Possible solutions
In the simplest case, there is maybe already a solution that I am just not aware of. I am ready to be educated on this :) Otherwise I can think of a couple of ways to work around this, but there might still be other ways to approach this.

- One could simply add an configurable option to skip all (or even just some) `masterIdentities` when encrypting something using `agenix edit`/`agenix generate`. Instead, the user can supply a manually assembled list of all the required identity pubkeys through the `extraEncryptionPubkeys` option. While this is more error-prone, I would assume that identities don't change that often, an so it wouldn't be a huge inconvenience. Still, it would put a larger burden on the user to manage their keys. This should be possible to implement in a way that is completely backwards compatible and will have no unexpected side effects for existing users, as it would be purely opt-in (maybe with a big warning that clarifies the risks of improper key management).
- Another way could be to try and be smart about it and parse the comments in the `masterIdentities` files to try and extract a pubkey to specify with `-r` instead of `-i`. However that would seem much more like a solution for upstream anyways, so I don't know that this would be a great option here. I certainly feels a lot more hacky and might mess with peoples setups in unanticipated ways.

Again, I would be happy to explore some of these options in a PR, but I would first like to know how you feel about this topic in general.

### PR DESCRIPTION
**Pull request by Lukas-C**
Fixes #24.

## Changes
First, the implementation introduces a new syntax for specifying identities in `age.rekey.masterIdentities`:
``` nix
{
  # This has the same type as the old way to specify an identity.
  identity = ./path-to-identity;
  # Optional; This has the same type as `age.rekey.hostPubkey`
  # and allows explicit association of a pubkey with an identity.
  pubkey = "age1yubikey1<pubkey>";
}
```
The old syntax continues to be supported through automatic coercion into the new format. If `pubkey` is specified, it will be used to encrypt files, instead of trying to extract a pubkey from the identity file.

Second, the implementation may extract an "implicit" pubkey from the identity file to use instead of the identity itself. This will only happen if the following conditions are met:

- The identity does not already specify `pubkey` using the above syntax.
- The identity file contains exactly one identity.
- The identity is of the form `AGE-PLUGIN-YUBIKEY-<...>`.
- The pubkey is specified in the form `Recipient: age1yubikey1<pubkey>`.
- Exactly one pubkey is found in the identity file. If there is more than one pubkey found, it is considered ambiguous and a hard error, since it may risk encrypting to unwanted (and possibly unsafe) pubkeys.

Every identity file that does not match all of the above criteria will be passed to (r)age without further processing, in order to let the program itself deal with the identity at runtime.

Third, the implementation adds support for the new environment variable `AGENIX_REKEY_PRIMARY_IDENTITY`, which is used during decryption. If set to a pubkey, agenix-rekey will attempt to locate the key amongst the explicitly and implicitly specified pubkeys:

- If the pubkey can be successfully matched, the associated identity file is specified in first place of the arguments passed to (r)age and will thus get the first attempt at decrypting the file. The order of the identities that follow remains untouched.
- If the pubkey cannot be matched, all identities are simply tried in order. A warning is printed during **both** encryption and decryption operations to inform the user about a potentially inconsistent configuration.

## Implementation
I ended up writing a wrapper script for (r)age in `./nix/lib.nix`  that is shared between for the encrypt and decrypt phases and decides what phase to run based on the first argument it receives. The remaining arguments are directly passed to (r)age. Warnings are deferred to stderr in order to not mess with generators that use the `decrypt` command in a piping fashion, e.g.:
``` nix
generator.script = "cat ${./secret.age} | ${decrypt}";
```

## Testing
The current code can successfully handle the following `flake.nix`. See the comments next to the different `masterIdentities` and `age.secrets` for further details:
``` nix
{
  inputs = {
    nixpkgs.url = "github:nixos/nixpkgs/nixpkgs-unstable";

    agenix = {
      url = "github:ryantm/agenix";
      inputs.nixpkgs.follows = "nixpkgs";
    };
    agenix-rekey = {
      #url = "github:oddlama/agenix-rekey";
      url = "github:Lukas-C/agenix-rekey";
      inputs.nixpkgs.follows = "nixpkgs";
    };
  };

  outputs = inputs@{ self, nixpkgs, agenix, agenix-rekey, ... }:
    let
      system = "x86_64-linux";
      pkgs = import nixpkgs { inherit system; };
    in {
      nixosConfigurations."test" = nixpkgs.lib.nixosSystem {
        modules = [
          agenix.nixosModules.default
          agenix-rekey.nixosModules.default
          {
            nixpkgs = { inherit system; };

            age.rekey = {
              storageMode = "local";
              localStorageDir = ./rekey;

              masterIdentities = [
                # Yubikey A, not plugged in
                ./identities/yubikey-a.pub

                # Yubikey B, plugged in
                ./identities/yubikey-b.pub

                ## Yubikey B, multiple pubkeys for one identity.
                ## Confirmed to fail, since this is not supported.
                #./identities/yubikey-b-multiple-pubkey.pub

                # Unencrypted plain `age` identity with a wonky name.
                # Can be used as-is, since the identity does not require further action,
                # even though this configuration should not be used.
                (./identities + "/test -i key.key")

                # Encrypted plain `age` identity, without an available pubkey.
                # Prompts for the passphrase, during both encryption and decryption.
                ./identities/testkeypass.key

                # (Same) encrypted identity with a pubkey.
                # Would only prompt for the passphrase during decryption.
                {
                  identity = ./identities/testkeypass.key;
                  pubkey = "age1w0reymggaakqgck6d8ndy635deh8p7eavaskpz0u48yqlad8v55qqum065";
                }
              ];
            };

            age.secrets = {
              # Basic secret file created with `agenix edit`.
              test = { rekeyFile = ./test.txt.age; };

              # Basic generated file to test `agenix generate`.
              test-generate = {
                rekeyFile = ./generate.age;
                generator.script = { ... }: "echo generator";
              };

              # Test proper behavior when piping into the `decrypt` command,
              # which is now a wrapper script around (r)age.
              # Requires setting AGENIX_REKEY_PRIMARY_IDENTITY to an invalid pubkey to test properly.
              # The resulting warning should not appear in the file as it is directed to stderr instead.
              test-generate-stdio = {
                rekeyFile = ./generate-stdio.age;
                generator.script = { decrypt, ... }: ''
                  cat ${./generate.age} | ${decrypt}
                '';
              };
            };
          }
        ];
      };

      agenix-rekey = agenix-rekey.configure {
        userFlake = self;
        nodes = self.nixosConfigurations;
      };

      devShells."x86_64-linux".default = pkgs.mkShell {
        packages = [ agenix-rekey.packages."x86_64-linux".default ];
      };
    };
}
```

### `AGENIX_REKEY_PRIMARY_IDENTITY` set to pubkey of Yubikey B
- `agenix edit`:
  1) Prompts for Yubikey B PIN for decryption.
  2) Prompts for `testkeypass.key` during encryption.
- `agenix generate -f`:
  1) Prompts once for Yubikey B PIN for decryption. The PIN is only prompted for once.
  2) Prompts for `testkeypass.key` for each generated secret during encryption.
- `agenix rekey -f`:
  1) Prompts once for specified Yubikey for decryption. The PIN is only prompted for once.

### `AGENIX_REKEY_PRIMARY_IDENTITY` unset
- `agenix edit`:
  1) Prompts for Yubikey A PIN for decryption. Prompts for Yubikey B PIN if the first is skipped and (r)age does not fail.
  2) Prompts for `testkeypass.key` during encryption.
- `agenix generate -f`:
  1) Prompts for Yubikey A PIN for decryption. Prompts for Yubikey B PIN if the first is skipped and (r)age does not fail. Will prompt for PIN of Yubikey B every time Yubikey A is skipped.
  2) Prompts for `testkeypass.key` for each generated secret during encryption.
- `agenix rekey -f`:
  1) Prompts for Yubikey A PIN for decryption. Prompts for Yubikey B PIN if the first is skipped and (r)age does not fail. Will prompt for PIN of Yubikey B every time Yubikey A is skipped.

### `AGENIX_REKEY_PRIMARY_IDENTITY` set to invalid pubkey
Behavior is the same as if unset. The following warning is printed at least once for every one of the three operations:
```
warning: Environment variable AGENIX_REKEY_PRIMARY_IDENTITY is set, but matches none of the pubkeys found by agenix-rekey.
warning: Please check that your pubkeys and identities are set up correctly.
warning: Value of AGENIX_REKEY_PRIMARY_IDENTITY: "test"
warning: Pubkeys found:
warning:   age1yubikey1<pubkey-a> for file "/nix/store/<hash>-source/identities/yubikey-a.pub"
warning:   age1yubikey1<pubkey-b> for file "/nix/store/<hash>-source/identities/yubikey-b.pub"
warning:   age1<pubkey> for file "/nix/store/<hash>-source/identities/testkeypass.key"
```

## TODO
- [x] Documentation

### CODE REVIEW

**Review by oddlama — COMMENTED** [review]
Thanks for the detailed explanation! I've already looked through your additions and the new script but I don't think I have anything to add at this point. This is looking pretty great already!

I guess you can just copy some parts of your PR description and put it in as documentation. All that's needed is probably a mention of the environment variable and an update to the `masterIdentities` option description to point out how it works now. For any more details I'd say you can just link to this PR.

I'm not sure which additional warnings you'd fancy? I'd definitely be fine with what you already have.

Thanks again!

**Comment by Lukas-C** [comment]
I was originally considering warnings that indicate a "potentially degraded" user experience, e.g. a warning if a Yubikey identity does not have an associated pubkey. However I think now that a proper explanation in the manual/readme is required anyways and will be sufficient. No need to create additional complexity where there doesn't have to be.

So if you are happy with the current state, I will only add the remaining documentation and leave the PR otherwise as is.

**Comment by Lukas-C** [comment]
I have now expanded the README and hope the explanations are clear enough so that people know what is possible, what to do and where to look.

Minor remarks:
- I had to omit some of the details of the new `masterIdentities` type signature, since readability otherwise would have suffered even more. Instead I made due with a link to the actual lines of code. At the moment it points to the location where the corresponding lines should end up after the merge, so we should probably update this to a proper permalink afterwards.
- I added a separate section for the new environment variable (and potential future ones). Since we're somehow still missing a terminal prompt emoji in the Unicode standard, I made due with a keyboard (⌨) as the section logo.

**Comment by oddlama** [comment]
> I have now expanded the README and hope the explanations are clear enough so that people know what is possible, what to do and where to look.

Looks good, thanks.

> Minor remarks:
> 
>     * I had to omit some of the details of the new `masterIdentities` type signature, since readability otherwise would have suffered even more. Instead I made due with a link to the actual lines of code. At the moment it points to the location where the corresponding lines should end up after the merge, so we should probably update this to a proper permalink afterwards.

I'll probably switch to mdbook rendered documentation at some point, then it will hopefully be more readable.

>     * I added a separate section for the new environment variable (and potential future ones). Since we're somehow still missing a terminal prompt emoji in the Unicode standard, I made due with a keyboard (⌨) as the section logo.

Good idea!

I think this is good to now, thanks again for all your work!

**Comment by Lukas-C** [comment]
Happy to contribute, thank you for your openness towards my suggestions and for the constructive discussion and feedback :D

**Pull request merged**
